### ISSUE TITLE
Сохранение и открытие xlsx в delphi

### ISSUE THREAD

**Issue by el-strannik** [Avemey/zexmlss#15]
Здравствуйте.

Что-то не понимаю как в последней версии теперь открывать файл в delphi. Раньше была функция ReadXSLX, а теперь она 
`{$IFDEF FPC}
function ReadXLSX(var XMLSS: TZEXMLSS; FileName: string): integer;
{$ENDIF}`
только для FPC.

Для сохранения тоже раньше использовал SaveXmlssToXLSX, теперь она для FPC.

**Comment by Avemey** [comment]
Re: [Avemey/zexmlss] ���������� � �������� xlsx � delphi (#15)






Ave el-strannik!


Чтобы из Delphi заработали упаковщики, нужно:
1. из папки zexmlss\delphizip\ выбрать нужный упаковщик (проще всего использовать abbreviazip: http://sourceforge.net/projects/tpabbrevia/) и скопировать из него файлы в zexmlss\src
2. Перекомпилировать компонент.

Более подробно тут:
http://avemey.com/zexmlss/delphizip.php?lang=ru

Вероятно, при новой установке были перезатёрты файлы odszipfunc.inc odszipfuncimpl.inc odszipuses.inc xlsxzipfunc.inc xlsxzipfuncimpl.inc xlsxzipuses.inc.

Thursday, July 13, 2017, 12:08:58 PM, you wrote:






Здравствуйте.
Что-то не понимаю как в последней версии теперь открывать файл в delphi. Раньше была функция ReadXSLX, а теперь она
{$IFDEF FPC} function ReadXLSX(var XMLSS: TZEXMLSS; FileName: string): integer; {$ENDIF}
только для FPC.
Для сохранения тоже раньше использовал SaveXmlssToXLSX, теперь она для FPC.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.








-- 
Best regards,
 Falcon                            mailto:avemey@tut.by
                                       http://avemey.com

**Comment by el-strannik** [comment]
Спасибо!
